---
abstract: 'represents the trading calendar.'
author:
  - 'binary.com <BINARY@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::FailWarnings: '0.008'
  Test::MockTime: '0'
  Test::More: '0.98'
  Test::Most: '0.34'
  Time::Local: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '7.64'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.029, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Finance-Calendar
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Finance::Calendar:
    file: lib/Finance/Calendar.pm
    version: '0.06'
requires:
  Carp: '0'
  Date::Utility: '0'
  Finance::Exchange: '0'
  List::Util: '0'
  Memoize: '0'
  Moose: '0'
resources:
  bugtracker: https://github.com/deriv-com/perl-Finance-Calendar/issues
  homepage: https://github.com/deriv-com/perl-Finance-Calendar
  repository: https://github.com/deriv-com/perl-Finance-Calendar.git
version: '0.06'
x_authority: cpan:DERIV
x_contributors:
  - 'Jun Bon <junbon@binary.com>'
  - 'Hafiz <hafiz@regentmarkets.com>'
  - 'Shahrizal Shaari <shahrizal@binary.com>'
  - 'Tom Molesworth <tom@binary.com>'
  - 'Jean-Yves Sireau <jy@binary.com>'
  - 'Torsten Förtsch <torsten@binary.com>'
  - 'Arash <61218785+arash-binary@users.noreply.github.com>'
  - 'Arun Venkataraman <arun@regentmarkets.com>'
  - 'chylli-deriv <52912308+chylli-deriv@users.noreply.github.com>'
  - 'qiangliu <52957232+qiangliu-binary@users.noreply.github.com>'
  - 'Tanvir Faisal <126654333+tanvir-deriv@users.noreply.github.com>'
  - 'yngshan-binary <yngshan@binary.com>'
x_generated_by_perl: v5.26.2
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
