name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        perl-version:
          - "5.24"
          - "5.26"
          - "5.28"
          - "5.30"
          - "5.32"
          - "5.34"

    steps:
    - name: Checkout Finance-Calendar
      uses: actions/checkout@v4
      with:
        path: perl-Finance-Calendar
      env:
        GH_EVENT: ${{ github.event_name }}
        GH_REF: ${{ github.ref_name }}
        PR_AUTHOR: ${{ github.event.pull_request.head.repo.owner.login }}
        PR_BRANCH: ${{ github.event.pull_request.head.ref }}
    
    - name: Determine Finance-Exchange repository and branch
      id: finance-exchange-info
      run: |
        if [ $GH_EVENT = "pull_request" ]; then
          echo "repository=$PR_AUTHOR/perl-Finance-Exchange" >> $GITHUB_OUTPUT
          echo "branch=$PR_BRANCH" >> $GITHUB_OUTPUT
        else
          echo "repository=deriv-com/Finance-Exchange" >> $GITHUB_OUTPUT
          echo "branch=$GH_REF" >> $GITHUB_OUTPUT
        fi
    
    - name: Checkout Finance-Exchange (try PR author's fork first)
      uses: actions/checkout@v4
      continue-on-error: true
      id: checkout-author-fork
      with:
        repository: ${{ steps.finance-exchange-info.outputs.repository }}
        ref: ${{ steps.finance-exchange-info.outputs.branch }}
        path: perl-Finance-Exchange
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Checkout Finance-Exchange (fallback to main repo master)
      uses: actions/checkout@v4
      if: steps.checkout-author-fork.outcome == 'failure'
      with:
        repository: deriv-com/perl-Finance-Exchange
        ref: master
        path: perl-Finance-Exchange
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl-version }}
    
    - name: Install cpanm
      run: |
        curl -L https://cpanmin.us | perl - --sudo App::cpanminus
    
    - name: Install dependencies
      run: |
        cd perl-Finance-Calendar
        cpanm -n --installdeps .
    
    - name: Setup Finance-Exchange share directory override
      run: |
        echo "PERL_FILE_SHAREDIR_DIST_Finance_Exchange=$PWD/perl-Finance-Exchange/share" >> $GITHUB_ENV
    
    - name: Run Tests
      run: |
        cd perl-Finance-Calendar
        prove -l t/
